export const Fonts = {
  regular: 'Inter-Regular',
  medium: 'Inter-Medium',
  semiBold: 'Inter-SemiBold',
  bold: 'Inter-Bold',
  poppinsRegular: 'Poppins-Regular',
  poppinsMedium: 'Poppins-Medium',
  poppinsSemiBold: 'Poppins-SemiBold',
  poppinsBold: 'Poppins-Bold',
  spaceRegular: 'SpaceGrotesk-Regular',
  spaceMedium: 'SpaceGrotesk-Medium',
  spaceSemiBold: 'SpaceGrotesk-SemiBold',
  spaceBold: 'SpaceGrotesk-Bold',
  playfairRegular: 'Playfair-Regular',
  playfairBold: 'Playfair-Bold',
  playfairItalic: 'Playfair-Italic',
  displayBold: 'Playfair-Bold',
  headingBold: 'Poppins-Bold',
};
