import { coreBackend } from './coreBackend';

export const supabase = coreBackend;

export type Profile = {
  id: string;
  email: string;
  full_name: string;
  phone: string | null;
  role: 'customer' | 'rider' | 'vendor' | 'admin';
  avatar_url: string | null;
  vendor_status: 'pending' | 'approved' | 'rejected' | null;
  business_name: string | null;
  business_description: string | null;
  business_address: string | null;
  business_phone: string | null;
  business_license: string | null;
  rejection_reason: string | null;
  is_suspended: boolean;
  suspended_at: string | null;
  suspended_by: string | null;
  location_lat: number | null;
  location_lng: number | null;
  location_address: string | null;
  location_updated_at: string | null;
  created_at: string;
  updated_at: string;
};

export type Order = {
  id: string;
  customer_id: string;
  vendor_id: string | null;
  vendor_user_id: string | null;
  order_number: string;
  status: 'pending' | 'confirmed' | 'preparing' | 'ready_for_pickup' | 'out_for_delivery' | 'delivered' | 'cancelled';
  subtotal: number;
  delivery_fee: number;
  tax: number;
  total: number;
  delivery_address: string;
  delivery_type: 'pickup' | 'delivery';
  payment_method: 'wallet' | 'online' | 'cash_on_delivery' | 'transfer';
  payment_status: 'pending' | 'completed' | 'failed';
  discount_amount: number;
  promo_code: string | null;
  promo_id: string | null;
  notes: string | null;
  confirmed_at: string | null;
  preparing_at: string | null;
  ready_for_pickup_at: string | null;
  out_for_delivery_at: string | null;
  delivered_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
  rider_id: string | null;
  assigned_rider_id: string | null;
  pickup_address: string | null;
  order_source: string | null;
};
